### ISSUE TITLE
disable insert mode ToggleTerm keybinding

### ISSUE THREAD

**Issue by goolord** [akinsho/nvim-toggleterm.lua#15]
would you be open to making the insert mode mapping configurable? https://github.com/akinsho/nvim-toggleterm.lua/blob/master/lua/toggleterm.lua#L264

I basically never want to make insert mode keybinds

**Comment by akinsho** [comment]
Should be pretty easy to add a configuration option for it, like `insert_mappings = true` by default and then you can wrap that block with a check to see what a user has set. I'm not gonna be able to get to it for a little while but it's a pretty small PR if you want to have a go at adding it.
