### ISSUE TITLE
Question: Change direction dynamically?

### ISSUE THREAD

**Issue by hahuang65** [akinsho/nvim-toggleterm.lua#17]
Is there a way for me to toggle a terminal, and then want to toggle another terminal, but in a different direction/orientation? It looks like right now, the direction is just hard-coded into the setup.

**Comment by akinsho** [comment]
@hahuang65 no, you currently can't dynamically swap terminal orientation. I didn't actually add the vertical orientation that was another user. I don't really know what that'd be useful for tbh, anyway my approach with this plugin is if someone has an idea for a feature that they want to add that isn't too complex or different from the stated goals of the project I'm happy to take a look.

From my perspective this doesn't really fit into the the things that I feel need to be added so I don't think I'd add this myself.

**Comment by hahuang65** [comment]
Thanks for the hard work so far! I'd love to see if I can make a PR but feel free to close this ticket if you want. I can always make a new PR ticket when I get around to it, if I get around to it.

**Comment by akinsho** [comment]
@hahuang65 👍🏿 I'll keep this open for a little while in case you or someone else gets to it and close it eventually if no one does

**Comment by zeertzjq** [comment]
Currently it seems different terminal can have different directions using `:ToggleTerm direction=`, however that only works for new terminals. The direction of existing terminals cannot be changed.
