### ISSUE TITLE
Exit insert mode from terminal

### ISSUE THREAD

**Issue by carlitux** [akinsho/nvim-toggleterm.lua#18]
How can we exit the insert mode when in terminal?

**Comment by akinsho** [comment]
@carlitux do you mean in neovim's terminal in general? that's documented under `:h terminal-input` but the TLDR is `<C-\><C-N>` I as well as most people have that remapped to something nicer but I didn't include stuff like that in this plugin since that's definitely a thing of personal preference

**Comment by akinsho** [comment]
@carlitux can I close this? is this still an issue you have? I might add some extra options to this plugin soon to add some of the mappings I have locally to this plugin for example automatically binding `<Esc>` in terminal mode etc.

**Comment by carlitux** [comment]
Yes, closing this I am using another toggle keymap and keep default exit mode

**Comment by AlphaTechnolog** [comment]
> Yes, closing this I am using another toggle keymap and keep default exit mode

How you do it?

**Comment by cybernet** [comment]
CTRL + d ( aka logout )
