### ISSUE TITLE
Allow the user to customize terminal size

### ISSUE THREAD

**Issue by ten3roberts** [akinsho/nvim-toggleterm.lua#2]
Currently, the terminal size is hardcoded in [plugin/toggleterm.vim](https://github.com/akinsho/nvim-toggleterm.lua/blob/master/plugin/toggleterm.vim) and [plugin/toggleterm.vim](https://github.com/akinsho/nvim-toggleterm.lua/blob/master/lua/toggleterm.lua) to 12 rows in the call to exec().

A variable like g:toggleterm_size could easily be created and allow the user to set their preference by feeding it to toggleterm.exec

Something similar could be done to the split direction to allow vsplit, although it'd require a bit more work.

**Comment by akinsho** [comment]
hey @ten3roberts yeah this is a hangover from me pulling this out of my dotfiles. Technically the exposed functions all take a `size` argument so you can map this to whatever you want. I'm going to have a look at refactoring this so all user preferences go into the setup call which I will externalise like

```lua
require"toggleterm".setup{ size = 20, open_mapping = "<C-G>" }
```

Regarding changing the way it opens, yep that will be a bit more work.

**Comment by akinsho** [comment]
@ten3roberts I've done a bit of a refactor to allow setting user preferences in the `setup` call which I've now made mandatory to initialize the plugin as a way to take a user's preferences. you can also set the split direction but the stacking remains

**Comment by ten3roberts** [comment]
Awesome. The new way is much, much better and keeps the lua-ness of the plugin with the setup.

I edited my nvim dotfiles and it is all working with a vertical 60 wide terminal without any bugs (splitting several and toggling works like a charm).
