### ISSUE TITLE
Question: Is it possible to set different keybindings to toggle different layouts with specific purposes ?

### ISSUE THREAD

**Issue by rafamadriz** [akinsho/nvim-toggleterm.lua#28]
Right now I'm using [vim-floaterm](https://github.com/voldikss/vim-floaterm) to spawn a terminal with lazygit like this:

![2021-Apr-26_1](https://user-images.githubusercontent.com/67771985/116089677-9e86c300-a692-11eb-9115-ce44b55f6b4b.png)

And that's the only thing I use floaterm for. It's just to have a nice integration of git inside neovim. Then I use toggleterm to toggle a terminal easily in a more classical horizontal  layout. 

However I wonder if I can achieve what I do with floaterm with just using toggleterm, which has more options like also spawning windows in floating mode. But I haven't figured out how to set custom keybindings to specific layouts or terminals. 

For example, to toggle the terminal I have `<A-t>` and for floaterm with the lazygit command I have `<leader>gg` , what I want to do is to set one specific keybind to toggle toggleterm in floating mode executing the lazygit command, and then my regular <A-t> for the terminal in horizontal layout. 

The problem I found is that the `open_mappings` option for toggling terminal is global, and it doesn't work for specific layouts with specific keybindings for those layouts. So if create a function to open toggleterm in floating mode and executing the lazygit command, then the toggle keybinding will only work for that specific terminal. 

So the question is: 
- Can I set an specific keybinding for different layouts/terminals ? 
- If it's not possible, How difficult is it to implement ?

**Comment by akinsho** [comment]
@rafamadriz good question, this is actually the main use case I actually implemented floating windows for. As well as refactoring the plugin's API to facilitate something like this. So I added the ability for users to create a specific terminal with specific commands which a user can create a mapping for. Here's an excerpt from my own config
```lua
        local lazygit =
          require("toggleterm.terminal").Terminal:new(
          {
            id = 100,
            cmd = "lazygit",
            direction = "float",
            on_open = function()
              vim.cmd("inoremap jk <Nop>")
            end
          }
        )
        as.nnoremap(
          "<leader>Lg",
          function()
            lazygit:toggle()
          end
        )
```

This way a user can create a specific terminal themselves with a specific command and toggle it via a mapping they create. There are still a few issues with it so I haven't publicised this functionality yet.

1. creating a terminal via `Terminal:new` will add it to the list of terminals so if you do it outside the mapping it will probably always be triggered first when you hit your normal open mapping, if you don't set an `id` which I don't want users to have to do.

2. Removing mappings inside of the newly opened terminal, this isn't really an issue with the plugin itself more that when you interact with something like lazy git you probably don't want your normal mappings around e.g. I use `jk` in insert mode to leave and so spamming `jk` in the `lazygit` terminal quits insert mode which is really annoying. I'd like to fix that somehow or offer an option to do so.

**Comment by rafamadriz** [comment]
<details><summary>...</summary>

> @rafamadriz good question, this is actually the main use case I actually implemented floating windows for. As well as refactoring the plugin's API to facilitate something like this. So I added the ability for users to create a specific terminal with specific commands which a user can create a mapping for. Here's an excerpt from my own config
> 
> ```lua
>         local lazygit =
>           require("toggleterm.terminal").Terminal:new(
>           {
>             id = 100,
>             cmd = "lazygit",
>             direction = "float",
>             on_open = function()
>               vim.cmd("inoremap jk <Nop>")
>             end
>           }
>         )
>         as.nnoremap(
>           "<leader>Lg",
>           function()
>             lazygit:toggle()
>           end
>         )
> ```
> 
> This way a user can create a specific terminal themselves with a specific command and toggle it via a mapping they create. There are still a few issues with it so I haven't publicised this functionality yet.

>   1. creating a terminal via `Terminal:new` will add it to the list of terminals so if you do it outside the mapping it will probably always be triggered first when you hit your normal open mapping, if you don't set an `id` which I don't want users to have to do.

>   2. Removing mappings inside of the newly opened terminal, this isn't really an issue with the plugin itself more that when you interact with something like lazy git you probably don't want your normal mappings around e.g. I use `jk` in insert mode to leave and so spamming `jk` in the `lazygit` terminal quits insert mode which is really annoying. I'd like to fix that somehow or offer an option to do so.
</details>

That's awesome, I'm gonna wait until that PR gets merged. Thanks for your work.

**Comment by rafamadriz** [comment]
Cool, it does adds the feature of setting custom keybindings to toggle custom terminals with specific commands and layouts. There's one minor thing that is annoying. When using something like this.
```lua
local Terminal = require("toggleterm.terminal").Terminal

local lazygit =
    Terminal:new(
    {
        cmd = "lazygit",
        direction = "float",
        hidden = true
    }
)

function _lazygit_toggle()
    lazygit:toggle()
end

vim.api.nvim_set_keymap("n", "<F5>", "<cmd>lua _lazygit_toggle()<CR>", {noremap = true, silent = true})
```
Once the terminal is open, you cannot toggle it while being in insert mode, you have to do the whole `<C-\><C-n>`  to go out of insert  mode and then you can toggle it with whatever key you have set. Then when you open that terminal once again, you have to manually go into insert mode again to be able to use that terminal.

This does not happen with the regular `open_mapping` option from the set up function of toggleterm. Whatever key you set in that option, can be used to toggle the terminal doesn't matter if you're in insert mode or not.

**Comment by akinsho** [comment]
@rafamadriz you have two options you can create a mapping inside this buffer that does that using the `on_open` command e.g.
```lua
on_open = function(term)
  api.nvim_buf_set_keymap(term.bufnr, "i", "<mapping>", "<c-\><-n>")
end
```

Or if you want the open mapping to work then don't use `hidden = true` and the terminal will be like other toggle terminals and respond to the open and close mapping
