### ISSUE TITLE
Add an explicit "install" section?

### ISSUE THREAD

**Issue by ajstrand** [akinsho/nvim-toggleterm.lua#30]
I'm pretty new to use using vim/neovim and still finding my way around installing plugins/editing my config. 

It seems like there's no consistent naming scheme for neovim/vim plugins, so I had to try a couple plugin names before the plugin installed successfully. 

Suggestion:
add an install section with directions like

> if you're using Packer as your plugin manager install this plugin using:

```lua
        use "akinsho/nvim-toggleterm.lua"
```

I'd be happy to contribute a PR if this is something worthwhile.

**Comment by akinsho** [comment]
@ajstrand thanks for raising the issue, I had completely forgotten it didn't have one tbh. regarding how to specify the name it's actually pretty standardised i.e. `username/repo-name` most plugin managers are just concatenating that to `github.com/%s` and calling git clone really. Anyway a PR would be fantastic. I think one showing using packer which is the one lua option I'd rather include and one showing vim plug for people using vimscript
