### ISSUE TITLE
[Feature request] Close terminal window on process exit

### ISSUE THREAD

**Issue by Chaitanyabsprip** [akinsho/nvim-toggleterm.lua#31]
Autoclose when we exit the terminal inside the buffer. if no terminal is running the buffer then it should delete the buffer and close the window

**Comment by Chaitanyabsprip** [comment]
So I checked, and  you're right,, even for me it is working the same, except when i do `jk` which is, for me, bound to exit into normal mode. and when I do, the window just stands there until I go back into terminal/insert mode and press a key

**Comment by akinsho** [comment]
@Chaitanyabsprip give #32 a try to see if it solves this

**Comment by Chaitanyabsprip** [comment]
@akinsho  I tested  the PR, It works great!
