### ISSUE TITLE
Prevent Esc Switching to Normal Mode

### ISSUE THREAD

**Issue by e-cal** [akinsho/nvim-toggleterm.lua#34]
When I use the plugin for a floating lazygit window I want to be able to press esc to cancel a commit, etc instead of being put in normal mode (not really useful in lazygit). I tried adding

```
    on_open = function(term)
        vim.api.nvim_buf_set_keymap(term.bufnr, 'i', '<Esc>', '<NOP>', {noremap = true, silent = true})
    end
```

but it doesn't seem to work. Any ideas?

**Comment by akinsho** [comment]
@e-cal this is likely because when you are in the terminal mode the correct mode should actually be `tnoremap` I have similar thing in my on open, but how I do it is
```lua
          on_open = function(term)
            vim.cmd("startinsert!")
            as.tnoremap("q", "<cmd>close<CR>", {buffer = term.bufnr, silent = false})
            if vim.fn.mapcheck("<esc>", "t") ~= "" then
              vim.api.nvim_buf_del_keymap(term.bufnr, "t", "<esc>")
            end
          end
```
Setting it to `<nop>` is probably not what you want since that will actually just make the `<esc>` key do nothing meanwhile what you want is for it to behave like a normal `<esc>`. Anyway the key is that you should use `:h tnoremap`

**Comment by e-cal** [comment]
Awesome thank you! Got it working now.

**Comment by jrafaaael** [comment]
> ```lua
>           on_open = function(term)
>             vim.cmd("startinsert!")
>             as.tnoremap("q", "<cmd>close<CR>", {buffer = term.bufnr, silent = false})
>             if vim.fn.mapcheck("<esc>", "t") ~= "" then
>               vim.api.nvim_buf_del_keymap(term.bufnr, "t", "<esc>")
>             end
>           end
> ```

Hello , @akinsho ! I trying this but I get the error: `attempt to index global 'as' (a nil value)`... How to solve this?

**Comment by akinsho** [comment]
@jrafaaael you can't copy the snippet verbatim you have to adapt it to your configuration. it contains helpers from my own config, namely the `as.tnoremap` is specific to my config you need to read the docs for `vim.api.nvim_buf_set_keymap` and use that instead

**Comment by jrafaaael** [comment]
@akinsho thank you! For anything with the same problem..:
```lua
local Terminal  = require('toggleterm.terminal').Terminal
local lazygit = Terminal:new({
  cmd = "lazygit",
  hidden = true,
  direction = "float",
  on_open = function(term)
    vim.cmd("startinsert!")
    vim.api.nvim_buf_set_keymap(0, "t", '<esc>', "<cmd>close<CR>", {silent = false, noremap = true})
    if vim.fn.mapcheck("<esc>", "t") ~= "" then
      vim.api.nvim_buf_del_keymap(term.bufnr, "t", "<esc>")
    end
  end,
})

function _lazygit_toggle()
  lazygit:toggle()
end

vim.api.nvim_set_keymap("n", "<leader>gg", "<cmd>lua _lazygit_toggle()<CR>", {noremap = true, silent = true})
```

**Comment by erlangparasu** [comment]
> @akinsho thank you! For anything with the same problem..:
> 
> ```lua
> local Terminal  = require('toggleterm.terminal').Terminal
> local lazygit = Terminal:new({
>   cmd = "lazygit",
>   hidden = true,
>   direction = "float",
>   on_open = function(term)
>     vim.cmd("startinsert!")
>     vim.api.nvim_buf_set_keymap(0, "t", '<esc>', "<cmd>close<CR>", {silent = false, noremap = true})
>     if vim.fn.mapcheck("<esc>", "t") ~= "" then
>       vim.api.nvim_buf_del_keymap(term.bufnr, "t", "<esc>")
>     end
>   end,
> })
> 
> function _lazygit_toggle()
>   lazygit:toggle()
> end
> 
> vim.api.nvim_set_keymap("n", "<leader>gg", "<cmd>lua _lazygit_toggle()<CR>", {noremap = true, silent = true})
> ```

Thanks!
