### ISSUE TITLE
Open mapping opens a second window

### ISSUE THREAD

**Issue by romgrk** [akinsho/nvim-toggleterm.lua#37]
Config:
```lua
require'toggleterm'.setup{
  size = 20,
  open_mapping = [[<c-space>]],
  shade_filetypes = {},
  shade_terminals = true,
  -- shading_factor = '<number>' -- the degree by which to darken to terminal colour, default: 1 for dark backgrounds, 3 for light
  start_in_insert = true,
  persist_size = true,
  -- direction = 'vertical' | 'horizontal',
}
```

After first mapping:
![Screenshot from 2021-05-10 08-09-17](https://user-images.githubusercontent.com/1423607/117656995-09da9580-b167-11eb-8c60-7ad98af0b59d.png)

After second mapping:
![Screenshot from 2021-05-10 08-09-22](https://user-images.githubusercontent.com/1423607/117657016-0e9f4980-b167-11eb-9072-8fabb9e23275.png)

Can't remember what was the previous time I updated but this started happening just after I updated just now.

**Comment by akinsho** [comment]
Hi @romgrk, do you have `set hidden` on in your config? if not this is one known thing that causes this issue. If you do already use that but are still seeing this can you try a minimal config with just this plugin and see if it still causes this issue

**Comment by romgrk** [comment]
Not reproducible with minimal config. Any idea what kind of issue might be causing this?

**Comment by akinsho** [comment]
@romgrk do you have an terminal related autocommands? I previously encountered this in #25 I think, the issue there being that that person didn't have `set hidden` on which meant when the terminal was being hidden it was being disposed of so every time it was triggered it wouldn't find the previous one.

In your screenshots it's appears to be trying to recreate terminal `1` each time, so it mustn't be finding it. Can you try toggling one terminal open, then running `require('toggleterm.terminal').get_all()` should return the map of all terminals. If it's empty then that would explain why the second toggle is creating a new term but not sure why the terminal wouldn't be being saved on open.

**Comment by akinsho** [comment]
No nothing off the top of my head other than I think something else must be set somewhere i.e. a vim setting I'm not thinking of or an autocommand, sorry no immediate ideas/suggestions other than the classic binary settings search

**Comment by romgrk** [comment]
Found it, custom `setf terminal` was conflicting with toggleterm's filetype.
