### ISSUE TITLE
Can I specify the path where terminal open from?

### ISSUE THREAD

**Issue by xaljer** [akinsho/nvim-toggleterm.lua#4]
Like open term from directory/git root/project root of current file?

**Comment by akinsho** [comment]
@xaljer currently you can't, I use this plugin by opening vim in the project dir so all terminals open with vim's `cwd` which is my project dir. If I need to move to a specific dir in a terminal I cd in that terminal. I *personally* don't think I would use/need to open a terminal at a directory that wasn't the main one I was working in, so not personally keen on implementing this.

It is a reasonable feature to have so will happily accept a PR that implements this though. I believe the best way to achieve this would be somehow allowing a directory to be specified in the `ToggleTerm` or a custom command, and then using that in the `termopen($SHELL, { cwd = arg_dir })`. I haven't properly explored this though so there's likely to be some edge cases

**Comment by xaljer** [comment]
my usage is that working in Android repo which contains many git repository. so i need to switch between various git.

**Comment by akinsho** [comment]
@xaljer I think it sounds like a reasonable addition, I just haven't got time to do this atm but will accept a PR otherwise I might look into in the future

**Comment by zhengpd** [comment]
I'm also trying to open terminal base on current project. ToggleTerm only supports `count` as term identity, so I compute a integer sum based on `getcwd()` and send it to ToggleTerm. Here is my script:

```lua
-- vim/lua/project_term.lua
local M = {}

local Terminal = require'toggleterm.terminal'.Terminal

M.toggle = function()
  local count = 0

  for char in string.gmatch(vim.api.nvim_eval("sha256(getcwd())"), '%S') do
    count = count + string.byte(char)
  end

  local term = Terminal:new({ count = count })

  term:toggle()
end

return M

-- nmap <silent> tt <Cmd>lua require('project_term').toggle()<CR>
```
