### ISSUE TITLE
Should delete buffer on process exit.

### ISSUE THREAD

**Issue by Chaitanyabsprip** [akinsho/nvim-toggleterm.lua#43]
I made a custom floating buffer and if I close the shell by doing `exit`, the buffer is taken off focus but is still hidden. When I toggle the custom floating terminal again, it shows the last session with a `[Process exited 0]` at the end of terminal. The expected behaviour should be to delete buffer on process exit.

**Comment by akinsho** [comment]
@Chaitanyabsprip I've noticed this as well, there have been some changes in neovim in how buffers in floating windows behave that have wreaked havoc in a few places, I think necessary changes but have lead to strange behaviour.

I'll ping you in a PR to see if that fixes things

**Comment by Chaitanyabsprip** [comment]
The above PR fixes this, so closing this issue now!
