### ISSUE TITLE
Plugin uses leader key in insert mode and normal mode

### ISSUE THREAD

**Issue by David-Else** [akinsho/nvim-toggleterm.lua#46]
```
let mapleader = "\<Space>"

" toggle line numbers                          < example, does not trigger in insert mode
nnoremap <silent><leader>n :set invnumber<CR>

lua <<EOF
require("toggleterm").setup{ size = 80, direction = 'vertical', open_mapping = [[<leader>t]] }
local Terminal  = require('toggleterm.terminal').Terminal
local lazygit = Terminal:new({ cmd = "lazygit", hidden = true, direction = "float" })

function _lazygit_toggle()
  lazygit:toggle()
end

vim.api.nvim_set_keymap("n", "<leader>g", "<cmd>lua _lazygit_toggle()<CR>", {noremap = true, silent = true})
EOF
```
When using `space` as the leader key now there is a delay after pressing every space in insert mode. The terminal can be toggled from insert mode, I assume this is an error as the leader key is expected to work from normal mode? I am not an expert in this, but that is how it works with all my other mappings.

With the above setup, whenever pressing space in insert mode Neovim acts as if there are potentially more keys in the sequence expected. It is like when you have `jk` as escape and press `j` then there is a delay while it waits to see if you press `k`. 

I have installed the latest nightly (Linux appimage):
```
nvim --version
NVIM v0.5.0-dev+1358-g192ea01ed
```

**Comment by akinsho** [comment]
@David-Else this plugin by default maps the open mapping in `normal` and `insert` mode. So the pause you see especially with a space leader is normal and unavoidable since space in insert mode will wait for the rest of any mappings. To work around this you can set the option `insert_mappings` (might need to cross check with the README) to false so this plugin won't create any insert mapping and so you won't see this issue.

**Comment by David-Else** [comment]
I set `insert_mappings = false` and it works :) This is not mentioned in the readme, it would be great if it were added.

In https://github.com/akinsho/nvim-toggleterm.lua#usage-1 you have an example advanced setting for lazygit.

```
local lazygit = Terminal:new({
  cmd = "lazygit",
  dir = "git_dir",
  direction = "float",
  float_opts = {
    border = "double",
  },
  -- function to run on opening the terminal
  on_open = function(term)
    vim.cmd("startinsert!")
    vim.api.nvim_buf_set_keymap(term.bufnr, "n", "q", "<cmd>close<CR>", {noremap = true, silent = true})
  end,
  -- function to run on closing the terminal
  on_close = function(term)
    vim.cmd("Closing terminal")
  end,
})
```
I tried it and the main difference was I now had an extra key to press to exit lazygit. are these settings recommend? I am not sure why you are setting `q` to quit when that works already by default in lazygit?

Final question. When I enter the lazygit UI my bindings `tnoremap jk <C-\><C-n>` are used, and mess up the down control `j` as there is the delay while it waits for `k`. Is it possible to remove this binding just for the lazygit terminal? That would be really cool. Cheers!

**Comment by David-Else** [comment]
Hi, sorry to keep asking questions in the issues section. I think I am almost sorted now,

When I enter lazygit in the custom terminal I need to disable insert mode mappings with `insert_mappings = false`, but I can't work out how to do it. The following doesn't work:

```
local lazygit = Terminal:new({ cmd = "lazygit", hidden = true, direction = "float", `insert_mappings = false` })
```
If I use `[space]t` in my commit message in lazygit at the moment it leaves lazygit and tells me there is no terminal to close.

What should I add to my setup below to disable insert mode mappings in the custom terminal?
```
lua <<EOF
require("toggleterm").setup{ size = 80, direction = 'vertical', open_mapping = [[<leader>t]], insert_mappings = false }
local Terminal  = require('toggleterm.terminal').Terminal
local lazygit = Terminal:new({ cmd = "lazygit", hidden = true, direction = "float" })

function _lazygit_toggle()
  lazygit:toggle()
end

vim.api.nvim_set_keymap("n", "<leader>g", "<cmd>lua _lazygit_toggle()<CR>", {noremap = true, silent = true})
EOF
```
THANKS!

**Comment by akinsho** [comment]
@David-Else I'm on mobile atm so can't answer properly. With regards to the insert mode mappings you have to unmap those yourself inside the on open function for the custom terminal. I have a similar thing in my dotfiles but I won't build it into the plugin because that presumed to much about a user's setup.

With regards to the insert mappings setting that should only need to be specified once at the top level config and would prevent insert mappings since it stops the autocommand that creates then from being set up

**Comment by akinsho** [comment]
Sorry didn't address the q mapping for lazygit since it's just an example I included the close mapping since it would be needed for other terminal applications and tbh this plugin didn't initially handle the q mapping from lazygit properly

**Comment by akinsho** [comment]
I'd also happily accept a PR about the missing docs for insert mapping I haven't got too much time on my hands atm

**Comment by David-Else** [comment]
I will have a look into making a PR regarding the insert mappings.

I found the section in your dot files regarding unmapping previously configured insert mode mappings and will try to use your settings, thanks!

> With regards to the insert mappings setting that should only need to be specified once at the top level config and would prevent insert mappings since it stops the autocommand that creates then from being set up

If you look at my config above I have `require("toggleterm").setup{ size = 80, direction = 'vertical', open_mapping = [[<leader>t]], insert_mappings = false }`. This stops the insert mappings in the `Terminal`, but not `lazygit`. Are you saying there is a bug, or is there something wrong with my config?

I really appreciate your time answering my questions, thanks!

**Comment by akinsho** [comment]
@David-Else this should now be fixed, turns out the mapping was being set in `tmap` mode which is the specific mode for inserting into the nvim terminal which is different to regular `imap` i.e. insert mode. Will close this out now 👍🏾 , lemme know if it didn't work for you (I tried with your leader key and it seemed to)
