### ISSUE TITLE
Question: How to toggle view with all the terminals?

### ISSUE THREAD

**Issue by LoydAndrew** [akinsho/nvim-toggleterm.lua#48]
Thanks for the great plugin. 
I have a question is there a way to have a command that toggles view with all the terminals that were created?
For example:
I created terminal with CTRl-\ than I created another terminal with a :ToggleTerm 2 
which leads to this view

![Screenshot_2021-06-04_12-44-39](https://user-images.githubusercontent.com/28489428/120782978-3bab0600-c533-11eb-9102-8a358e7dfa0f.png)

Than I want to hide all terminals (`:ToggleTerm all`  alike) and continue to work on editing files and after some time to toggle it again and have same view as before - 2 terminals bellow editing window (cause now CTRL -\ will only toggle one of the terminals, not all of them). 
This behaviour is similar to tmux prefix-z command which toggles maximize one pane. Or something like toggle terminal in heavy IDE-s like vscode, idea etc.

**Comment by akinsho** [comment]
@LoydAndrew that's a cool idea tbh I hadn't really considered it ever. There isn't really a way to do that currently but I like the idea. I think a reverse command would be good as well i.e. toggle all with none open opens all the previously opened and then using that again toggles them all.

It wouldn't be too hard to implement basically could add a check for the `all` argument to the toggle term commannd and then loop through all terminals and call toggle. I guess the potentially weird edge case would be if one terminal was open and you hit `TermToggle all` should that open the rest or close the open one.

Maybe in that case it should work more explicitly `ToggleTermCloseAll` or `ToggleTermOpenAll` and then it can be explicitly mapped to opening any that aren't open or just closing them all.

Anyway I'd be happy to help direct a PR for this, most of the logic to do this is already there just needs commands defined and cobble thing together

```vim
" in toggleterm.vim
command! ToggleTermCloseAll lua require('toggleterm').toggle_all('close')
command! ToggleTermOpenAll lua require('toggleterm').toggle_all('open')
```
Then in `toggleterm.lua`

```lua
function M.toggle_all(command)
  for _, term in get_all() then
    if direction == "close" then
      term:close()
    else
      if not term:is_open() then
       term:toggle()
      end
    end
  end
end
```

**Comment by akinsho** [comment]
@LoydAndrew it was pretty straightforward to do i.e. more or less exactly what I had above so I just did it in my lunch break. Can you test it out and see if it works

**Comment by LoydAndrew** [comment]
@akinsho 
Thanks, great and quick work. I guess the only problem is to have 2 explicit commands rather then one toggle, but I can live with that. Again, very appreciate it.

**Comment by akinsho** [comment]
@LoydAndrew if you had only one command and had 1 window open it not clear how it should work. Should it close that window or open other windows you previously toggled 🤷🏾‍♂️  I'm definitely open to a PR to fix it though but I probably won't spend more time on it myself, this isn't really a workflow I use
