### ISSUE TITLE
Emoji go through floating terminal

### ISSUE THREAD

**Issue by Nguyen-Hoang-Nam** [akinsho/nvim-toggleterm.lua#61]
At first, I think this is problem with neovim, but telescope work fine.

![normal](https://user-images.githubusercontent.com/74345759/125940934-f69a2f6e-78e2-4386-a46a-fb018f8b4242.png)

![terminal](https://user-images.githubusercontent.com/74345759/125941095-c8e8de6f-f87c-44b0-9bc4-b6eda1ac6631.png)

![telescope](https://user-images.githubusercontent.com/74345759/125941106-d5267f9f-0a94-4180-8c68-372ff6ad935c.png)

**Comment by akinsho** [comment]
@Nguyen-Hoang-Nam I believe this is actually an upstream issue. The reason you don't see it in telescope is that by default this plugin uses a `winblend` to make the window slightly transparent. Using winblend causes this issue, not sure why but will have something to do with terminal rendering and multigrid in nvim probably. Can you try setting winblend to 0 and seeing if that resolves your issue.

```lua
require('toggleterm').setup{
	float_opts = {
  		winblend = 0, -- <-- set to 0
	}
}
```
