### ISSUE TITLE
Error starting terminal OutOfProcessMediatorBasse

### ISSUE THREAD

**Issue by jtourlamain** [akinsho/nvim-toggleterm.lua#65]
I'm using neovim (v0.5.0) on windows. 
My shell is set to pwsh.exe. Starting a default terminal (so not using the plugin) works via the command :terminal

When using the plugin I get a quick error message before the terminal is closed:

```
at System.Management.Automation.Remoting.OutOfProcessUtils.ProcessData(String data, DataProcessingDeleegates callback)
at System.Management.Automation.Remoting.Server.OutOfProcessMediatorBase.ProcessingThreadStart(Object state)
```

I didn't change the default config a lot:

```
require("toggleterm").setup{
  function(term)
    if term.direction == "horizontal" then
      return 15
    elseif term.direction == "vertical" then
      return vim.o.columns * 0.4
    end
  end,
  open_mapping = [[<Leader>t]],
  hide_numbers = true, 
  shade_filetypes = {},
  shade_terminals = true,
  shading_factor = '1', 
  start_in_insert = true,
  insert_mappings = true, 
  persist_size = true,
  direction = 'float', 
  close_on_exit = true, 
  shell = "pwsh.exe", 
  float_opts = {
    border = 'single', 
    width = 80,
    height = 100,
    winblend = 3,
    highlights = {
      border = "Normal",
      background = "Normal",
    }
  }
}
```

**Comment by akinsho** [comment]
Hi @jtourlamain, thanks for reporting this. So I'm quite unfamiliar with windows or how it or it's shells work. So I don't really have any clue what to make of the error. By default this plugin uses the value of `vim.o.shell` which should be the same as the terminal. It also works by calling `vim.fn.termopen` which should be quite similar to just calling `:terminal`.

can you verify what a plain `:lua vim.fn.termopen()` does for you? also maybe try changing the value of the `shell` to what it should be using `pwsh.exe` or to something like `bash` 🤷🏿‍♂️ .Sorry I can't really offer too much help here, this is completely foreign territory to me.

**Comment by jtourlamain** [comment]
I tried with `vim.o.shell` but it has the same result. Executing the command `:lua vim.fn.termopen()` results in an error:

```
E5108: Error executing lua vim:E119: Not enough arguments for function: termopen
```

Does it mean I forgot some configuration?

**Comment by akinsho** [comment]
@jtourlamain sorry that wasn't the full command, that was more of a pointer than the explicit full thing to use you can see the docs for termopen using `:help termopen` I believe it requires a cmd argument, so you can do `lua vim.fn.termopen(vim.o.shell)` please read the term open doc though in case I missed something else though.

**Comment by akinsho** [comment]
@jtourlamain any news on this? did you manage to try the term open function to see how that behaves?
Will check back in in a few days and if I don't here from you I will close this out. This is definitely not something I can fix without input from a windows user also experiencing this.

**Comment by jtourlamain** [comment]
@akinsho I found out that the problem is not caused by this repo. I had the same problem using vim-floaterm. Using bash wasn't problem.
