### ISSUE TITLE
[Bug] horizontal term should close if it is the last window

### ISSUE THREAD

**Issue by qvieth** [akinsho/nvim-toggleterm.lua#67]
E5108: Error executing lua ...ack/packer/opt/nvim-toggleterm.lua/lua/toggleterm/ui.lua:256: Vim:E444: Cannot close last window
This was thrown when I was trying to exit from a file buffer while a horizontal toggle term instance is opening
Expected behavior :wq on file buffer exit both file buffer and the horizontal toggle term.

**Comment by qvieth** [comment]
file:///home/qvieth/Videos/Screencast%20from%2007-21-2021%2004:02:15%20PM.webm

**Comment by qvieth** [comment]
https://user-images.githubusercontent.com/71810726/126462620-3f6f41ec-d95a-4df8-a3c1-8ba9aa140fc1.mp4

**Comment by akinsho** [comment]
@qvieth this is partially a duplicate of #64, I've left it open though because a split window should technically not remain open if the other neighbouring window was closed. FWIW this is not how I envisioned people using the plugin or how I use it, till I or someone else gets a chance to fix this it is better if you *close the terminal* before closing the other buffer.

**Comment by qvieth** [comment]
@akinsho Thank you, really appreciate your works on this plugin

**Comment by akinsho** [comment]
The error should now no longer appear, but the automatic closing of the terminal if it is the last window doesn't work yet

**Comment by qvieth** [comment]
@akinsho I just did an upgrade but that error still appeared as same as before

**Comment by qvieth** [comment]
@akinsho i just did an upgrade but the error still appeared to be the same as before

**Comment by akinsho** [comment]
Oh, sorry this isn't actually a duplicate of the error I referenced before, ignore that then the status of this is the same as before then.

**Comment by akinsho** [comment]
@qvieth this should now be fixed by the most recent commit on master, it works by choosing another buffer using `bnext` if a user closes the neigbouring window

**Comment by qvieth** [comment]
So cool! Thank you so much @akinsho, Toggleterm works flawlessly for me now!
