### ISSUE TITLE
[Bug] Floating windows don't auto open on exec

### ISSUE THREAD

**Issue by will** [akinsho/nvim-toggleterm.lua#68]
Following up from https://github.com/akinsho/nvim-toggleterm.lua/issues/62#issuecomment-885187362

Summary: when I was using `require('toggleterm').exec(...)` to run something with [this configuration](https://github.com/ChristianChiarulli/LunarVim/blob/95aa1ea8c6b8dc31bae26fe1d433e83f57dd4201/lua/core/terminal.lua#L2), the floating terminal would not auto open 

@<i></i>akinsho said:
> Seems term exec doesn't open a float like it does for splits since it doesn't really seem to take the direction into consideration, maybe.

**Comment by zeertzjq** [comment]
I think it is caused by `go_back = true` in `Terminal:send().
