### ISSUE TITLE
How can I start terminal on Insert mode

### ISSUE THREAD

**Issue by FabioRamatis** [akinsho/nvim-toggleterm.lua#7]
I tried this autocmd

```vim
autocmd TermOpen * startinsert
autocmd TermLeave * stopinsert
```
But It only enters insert mode on the first opening, when I toggle down and toggle up again, it starts on normal mode

https://asciinema.org/a/AOjS5IuzDJE4sk8KSQcE183TP

**Comment by akinsho** [comment]
@FabioRamatis you can setup autocommands in your `init.vim` or `init.lua` like
```
  autocmd BufEnter * if &buftype ==# 'terminal' | startinsert! | endif
```
This will automatically put you in insert mode on entering a terminal buffer

**Comment by FabioRamatis** [comment]
Thank you! It worked

**Comment by akinsho** [comment]
@FabioRamatis I actually just added  this as feature to toggle term i.e. so without that setting it should now start in insert mode automatically

**Comment by FabioRamatis** [comment]
Awesome! thank you very much
