### ISSUE TITLE
Ugly p10k prompt inside floating toggleterm

### ISSUE THREAD

**Issue by qvieth** [akinsho/nvim-toggleterm.lua#70]
![image](https://user-images.githubusercontent.com/71810726/126895257-3229b4df-7c90-49d5-aabc-45ae28d734fe.png)

This wasn't the case with vimfloaterm or Fterm.nvim, anyway to fix this?

**Comment by qvieth** [comment]
![image](https://user-images.githubusercontent.com/71810726/126895360-09bb6df0-f092-410a-b017-8402827145a0.png)

here's my prompt in Fterm.nvim

**Comment by akinsho** [comment]
@qvieth maybe disable the winblend option and see if that improves things. Details on that option are in the README configuration.

**Comment by qvieth** [comment]
Thank you, @akinsho, changed the winblend option to 0 fixed the issue for me
