### ISSUE TITLE
are the terminals persistant with process in running ?

### ISSUE THREAD

**Issue by devewok** [akinsho/nvim-toggleterm.lua#73]
If i run an nodejs server api in terminal, does can it persist that process ?

**Comment by akinsho** [comment]
@devewok if you have set `hidden` which is a required setting for this plugin then terminal processes should be persisted, since the terminal should continue to run in the background. You can check `:h terminal` for more information of how terminal work in nvim.

**Comment by akinsho** [comment]
Going to close this as I believe it's been answered, i.e. yes, so long as hidden is set
