### ISSUE TITLE
Integrating with Vim-Test

### ISSUE THREAD

**Issue by olimorris** [akinsho/nvim-toggleterm.lua#86]
For reference, I integrated this with `vim-test` with the following snippet:

```lua
vim.api.nvim_exec([[

function! RunTermExec() abort
  return 'TermExec cmd='
endfunction

function! TermToggleStrategy(cmd) abort
  exec RunTermExec() . "'" . a:cmd . "'"
endfunction

let g:test#custom_strategies = {'toggleterm': function('TermToggleStrategy')}

]], false)

g['test#strategy'] = 'toggleterm'
```

Could not get the damn thing to work with just pure Lua so had to default to VimScript (puke emoji)

**Comment by olimorris** [comment]
@akinsho happy to make a pull on the readme

**Comment by akinsho** [comment]
@olimorris thanks for the snippet 👍🏿 tbh I've been considering making a PR to `vim-test` for quite a while but a) haven't had much time b) didn't know if some miraculous lua competitor would emerge but I think official support in vim test which is the defacto testing plugin for vim would be ideal. Regarding this snippet though, could the following snippet work, which is slightly more lua-y/less verbose?
```lua
vim.api.nvim_exec([[
function! TermToggleStrategy(cmd) abort
  v:lua.require('toggleterm').exec(cmd)
  " or 
  lua require('toggleterm').exec(cmd)
endfunction

let g:test#custom_strategies = {'toggleterm': function('TermToggleStrategy')}

]], false)

g['test#strategy'] = 'toggleterm'
```
There no way round the funcref issue for the custom strategy though which is fine.

**Comment by akinsho** [comment]
Happy to have a snippet in the README till there's official `vim-test` support, but not sure when I'll have time to do that 😆

**Comment by olimorris** [comment]
I too have been waiting for an `nvim-test` to emerge 😄 . The rate of new Lua plugins that hit the neovim subreddit is insane, so who knows. I see that `vim-test` have approved some core Neovim strategies in the last week!

So this was the best I could do (also tidying up my horrible naming):
```lua
vim.api.nvim_exec([[
function! ToggleTermStrategy(cmd) abort
  execute "lua require('toggleterm').exec('" . a:cmd . "', 1)"
endfunction

let g:test#custom_strategies = {'toggleterm': function('ToggleTermStrategy')}
]], false)

g['test#strategy'] = 'toggleterm'
```

Still verbose but at least we're calling Lua.

**Comment by akinsho** [comment]
Feel free to make a PR to add this to the README btw till I have some time to make an official PR to vim-test 👍🏿

**Comment by akinsho** [comment]
I tweaked it a little more on my end and added it to my dotfiles the only real change is the use of luaeval to avoid the string concatenation bit, so it's slightly more readable, although that's definitely debatable.

```lua
        vim.cmd [[
          function! ToggleTermStrategy(cmd) abort
            call luaeval("require('toggleterm').exec(_A[1], _A[2])", [a:cmd, 0])
          endfunction

          let g:test#custom_strategies = {'toggleterm': function('ToggleTermStrategy')}
        ]]

        vim.g['test#strategy'] = 'toggleterm'
```
NB: the second `0`  is a hack for a bug I'm going to fix soon where the terminal number is required, but actually you can do without it and toggleterm will use the last created terminal

I think it shouldn't be too hard to PR to vim-test. It will more or less be the code above, but one thing I think would be good to have as well would be a way to specify which terminal to use for testing. I wonder if vim-test allows specifying a variable like `let test#strategy#toggleterm#id = 3` or something
